server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 39.103.151.81:1111
management:
  endpoints:
    web:
      exposure:
        include: '*'
