server:
  port: 2002

spring:
  application:
    name: seata-storage-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_storage?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

logging:
  level:
    io:
      seata: info

mybatis-plus:
    mapperLocations: classpath:mapper/*.xml


seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: 127.0.0.1:8848
      group: SEATA_GROUP
      userName: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      application: seata-server
      serverAddr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace:
      userName: "nacos"
      password: "nacos"
