server:
  port: 80

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: false
    service-url:
    #单机版
     defaultZone: http://localhost:7001/eureka

ribbon:
  #建立连接从服务器读取资源所用时间
  ReadTimeout: 5000
  #建立连接所用时间
  Connectimeout: 5000
#  用于服务降级，在注解@FeignClient中添加fallbackFactory注解
feign:
  hystrix:
    enabled: true