server:
  port: 9527
spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
        discovery:
          locator:
            enabled: true            #开启从注册中心动态创建路由的功能，利用微服务名进行路由
        routes:
        - id: payment_routh                 #路由id，没有固定规则但是要唯一，建议配合服务名
          #uri: http://localhost:8001         #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**          #断言 路径匹配的进行路由


        - id: payment_routh2
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
            - After=2020-08-03T15:15:53.498+08:00[Asia/Shanghai]    #2020-08-03T15:15:53之后才能访问
            #- Cookie=username,zzyy                                   #cookie带上username=zzyy才能访问


eureka:
  instance:
    hostname: cloud-gatway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka

